### PR TITLE
fix: Improve CLI parsing for Image Args

### LINKED ISSUE #827: Unable to use the "--env" option on finch container run
**Describe the bug**
 Cannot use `--env` option

**Steps to reproduce**

```sh
finch container run -it --rm --env="E=v" busybox env
```

**Expected behavior**

```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
HOME=/root
E=v
```

**Screenshots or logs**

Actual result

```
FATA[0000] unknown shorthand flag: 'e' in -e
```

**Additional context**

Note: Updated to Finch 1.1.2 -- error still present

As a test I ran `nerdctl` (installed via Rancher Desktop) and it worked as expected

```sh
$ nerdctl container run -it --rm --env="E=v" busybox env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
E=v
TERM=xterm
HOME=/root
```

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._
[finch-support-20240222101339.zip](https://github.com/runfinch/finch/files/14366120/finch-support-20240222101339.zip)

### PR DESCRIPTION
**Pull request by chews93319**
Issue #, if available:  Resolves #827

*Description of changes:*

Evaluate CLI args according to positional group.
<args_before_options><option_args><image_name><image_args>

This change introduces:
 - Initial scan to identify the position of <option_args>
 - Handling cases for various Flag permutations
 - Function to handle various Flag&Argument permutations
 - Pass through handling for Image and Image Arguments
 - Associated Unit Test updates for new nerdctl output standards

*Testing done:*

- Successful `make test-unit` & `make test-e2e`
- manual testing with permutations of the commands listed below

```bash
./_output/bin/finch --debug container run -it --name="myContainer" -e "E=v" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug container run -it --name="myContainer" -e"E=v" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug container run -it --name="myContainer" --env="E=v" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug container run -it --name="myContainer" --env-file=temp.env --rm busybox echo -e "hello\tbye"

./_output/bin/finch --debug container run -it --env-file=temp.env --rm busybox env
./_output/bin/finch --debug container run -it --env="E=v" --rm busybox env
./_output/bin/finch --debug container run -it -e "E=v" --rm busybox env
./_output/bin/finch --debug container run -it -e"E=v" --rm busybox env

./_output/bin/finch --debug run -it -e"E=v" --rm busybox env
./_output/bin/finch --debug run -it -e "E=v" --rm busybox env
./_output/bin/finch --debug run -it --env="E=v" --rm busybox env
./_output/bin/finch --debug run -it --env-file=temp.env --rm busybox env

./_output/bin/finch --debug run -it --env-file=temp.env --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug run -it --env="E=v" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug run -it -e "E=v" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug run -it -e"E=v" --rm busybox echo -e "hello\tbye" env

./_output/bin/finch --debug run -it -e"USER" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug run -it -e "USER" --rm busybox echo -e "hello\tbye"
./_output/bin/finch --debug run -it --env="USER" --rm busybox echo -e "hello\tbye"
```

- [X] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: e2e/vm/soci_test.go [hunk 1]
```diff
@@ -98,7 +98,7 @@ var testSoci = func(o *option.Option, installed bool) {
 				"- soci\nvmType: %s\nrosetta: false", vmType)))
 			command.New(o, virtualMachineRootCmd, "init").WithoutCheckingExitCode().WithTimeoutInSeconds(160).Run()
 			port = fnet.GetFreePort()
-			command.New(o, "run", "-dp", fmt.Sprintf("%d:5000", port), "--name", "registry", registryImage).
+			command.New(o, "run", "-d", "-p", fmt.Sprintf("%d:5000", port), "--name", "registry", registryImage).
```
Comment (pendo324) [inline e2e/vm/soci_test.go:101]: Why'd we have to change this?

File: cmd/finch/nerdctl.go [hunk 2]
```diff
@@ -142,95 +143,202 @@ func (nc *nerdctlCommand) run(cmdName string, args []string) error {
...
+			if lastOpt {
+				cmdArgs = append(cmdArgs, arg)
+				continue
 			}
 
-			shouldSkip, addEnvs, err := handleEnvFile(nc.fs, nc.systemDeps, arg, args[i+1])
-			if err != nil {
-				return err
+			// scan the arg to separate shortFlag combinations of boolFlag and argFlag
+			re := regexp.MustCompile(`^-[a-z^-]+[ehmuwplv]$`)
```
Comment (pendo324) [inline cmd/finch/nerdctl.go:197]: If nerdctl adds a new bool/short flag, do we then have to update this regexp?

File: e2e/vm/soci_test.go (hunk 1 above)
Comment (chews93319) [reply e2e/vm/soci_test.go:101]: I changed that temporarily when I first encountered the implicit requirement to handle concatenated short flags.
I must have missed this test line when I was changing them back.

I will return this to the `-dp 8080:5000` version.

File: cmd/finch/nerdctl.go (hunk 2 above)
Comment (chews93319) [reply cmd/finch/nerdctl.go:197]: This regex, `shortFlagBoolSet` (line 160), the `longFlagBoolSet` (line 161-164), and the `shortFlagArgsSet` (in line165) are all susceptible to changes with the short flags.

To be honest, this regex was a "proof of concept" for handling the qty.3 enforcement goals in one line.
However, I would be easily convinced to refactor this to use the clearly defined sets (lines 160-165).

Comment (chews93319) [reply cmd/finch/nerdctl.go]: While refactoring this code, I also made an improvement for dynamically handling miscellaneous shortFlagBool combinations.

File: cmd/finch/nerdctl.go [hunk 3]
```diff
@@ -142,95 +142,224 @@ func (nc *nerdctlCommand) run(cmdName string, args []string) error {
...
+					case i == lastPos && shortFlagArgsSet.Has("-"+c):
+						argFlagFinal = true
+					default:
+						if shortFlagArgsSet.Has("-" + c) {
+							argFlagMid = true
+						}
+					}
+				}
+				switch {
+				case argFlagMid:
```
Comment (pendo324) [inline cmd/finch/nerdctl.go:257]: Can we get rid of this case and handle it in the preceding for loop?

Comment (chews93319) [reply cmd/finch/nerdctl.go:257]: - describe my reasoning; acknowledge pertinence
- propose pass odd case through to nerdctl validation

Thanks for the comment. I believe that you are highlighting the possibility of "Error Immediately on Mid Position Detection" and your observation is appropriate for potential optimization.

I similarly considered interrupting immediately, but thought that it may be more clear to have an explicit reaction case. Additionally, I intentionally wanted to "set the runway" if we need to take any additional action to "gracefully" handle the situation.

While we are focusing on this piece of code, I will iterate on this to uniquely print the debug statement, but to ultimately pass this case through to nerdctl arg validation.

File: cmd/finch/nerdctl.go [hunk 4]
```diff
@@ -142,95 +142,224 @@ func (nc *nerdctlCommand) run(cmdName string, args []string) error {
...
+		shortFlagBoolSet := sets.NewString("-d", "-i", "-t")
+		longFlagBoolSet := sets.NewString(
+			"--detach", "--init", "--interactive", "--oom-kill-disable",
+			"--privileged", "--read-only", "--rm", "--rootfs", "--tty")
+
+		shortFlagArgsSet := sets.NewString("-e", "-h", "-m", "-u", "-w", "-p", "-l", "-v")
+
+		for i, arg := range args {
+			// Check if command requires arg handling
+			if hasArgHandler {
```
[the remark this answers is not in the document]
Comment (chews93319) [reply cmd/finch/nerdctl.go:166]: Thanks for the comment. I believe that you are highlighting the precedence of the cmdHandler and argHandler paradigm.

After finding the nerdctl_windows implementation, I explored the current mechanisms for inspiration for my current change set. My primary observation was that the model was primarily positioned for "in place" argument manipulation/updating. Whereas, the actual argument&value processing (passing to resulting runArguments) was wholly contained here.

I agree that there is an optimization case for "command specific argument&value processing", specifically the possibility of cmdFlagSets and generalized processing helper functions.
In this case, I have attempted to deliver a "small unit" incremental change to address the scope of the Issue description, rather than a drastic refactor.

My next iteration leverages a bit of generalization for the FlagSets and an improved "short flag group" handler that will set the stage for another incremental refactor for further command specific argument&value processing.

[the remark this answers is not in the document]
Comment (pendo324) [reply cmd/finch/nerdctl.go:166]: Thanks, the code is a lot more readable now

File: cmd/finch/nerdctl.go [hunk 5]
```diff
@@ -501,3 +676,27 @@ var nerdctlCmds = map[string]string{
 	"volume":    "Manage volumes",
 	"wait":      "Block until one or more containers stop, then print their exit codes",
 }
+
+var cmdFlagSetMap = map[string]map[string]sets.Set[string]{
```
Comment (cezar-r) [inline cmd/finch/nerdctl.go:680]: nit: all 3 of these maps are identical, is there a reason to have separate copies for each command name?

**Review by cezar-r — APPROVED** [review]

File: cmd/finch/nerdctl.go (hunk 5 above)
Comment (chews93319) [reply cmd/finch/nerdctl.go:680]: Technically, each of the commands have distinct sets of flags.
However, with this first commit, I've maintained parity with the previous functionality.

This actually sets the stage for improved, nuanced handling of the various flag options for each of the present commands and any additional commands we may need to add.

Additionally, the implementation precedence within this file has established a certain amount of custom implementation for cli parsing rather than extending the dependency upon COBRA to functionally parse the cli elements.
We may or may not continue expanding our custom implementation, but that requires another level of design/plan effort.

Comment (cezar-r) [reply cmd/finch/nerdctl.go:680]: Makes sense, figured it was most likely to provide extensibility to each of these commands having their own unique set of flags in the future.
