### PR TITLE
ci(bug-fix): use local registry for VZ/Rosetta tests

### LINKED ISSUE #322: Fix test failure when running Rosetta tests
**Describe the bug**
The Rosetta tests added #282 are failing ([example](https://github.com/runfinch/finch/actions/runs/4545132549/jobs/8012048120?pr=282#logs)).

It may just be because they are running after QEMU and Virtualization.framework tests in sequence, it may just be some flakiness only observed when Rosetta is enabled, or it may be something else entirely.

**Steps to reproduce**
`make test-e2e` on a macOS 13+ AMD64 system, with Rosetta enabled, while having a Finch config (`~/.finch/finch.yaml`) which contains the following:
```yaml
...
vmType: vz
rosetta: true
...
```

**Expected behavior**
Tests should pass.

**Screenshots or logs**
https://github.com/runfinch/finch/actions/runs/4545132549/jobs/8012048120?pr=282#logs:
```
 Virtualization framework Virtualization framework and Rosetta Run a container image with --rm flag, container should be removed when it exits
/Users/ec2-user/go/pkg/mod/github.com/runfinch/common-tests@v0.6.2/tests/run.go:70
  No containers to be removed
  No images to be removed
  No volumes to be removed
  bridge
  host
  none
  No networks to be removed
  public.ecr.aws/docker/library/alpine:latest: resolving      |--------------------------------------| 
  elapsed: 0.1 s                               total:   0.0 B (0.0 B/s)                                         
  public.ecr.aws/docker/library/alpine:latest:                                      resolved       |++++++++++++++++++++++++++++++++++++++| 
  index-sha256:ff6bdca1701f3a8a67e328815ff2346b0e4067d32ec36b7992c1fdc001dc8517:    done           |++++++++++++++++++++++++++++++++++++++| 
  manifest-sha256:c41ab5c992deb4fe7e5da09f67a8804a46bd0592bfdf0b1847dde0e0889d2bff: done           |++++++++++++++++++++++++++++++++++++++| 
  config-sha256:d74e625d91152966d38fe8a62c60daadb96d4b94c1a366de01fab5f334806239:   done           |++++++++++++++++++++++++++++++++++++++| 
  elapsed: 0.2 s                                                                    total:   0.0 B (0.0 B/s)                                         
  time="2023-03-28T16:33:41Z" level=fatal msg="name \"ctr-test\" is already used by ID \"3c08eb578b671caefc48cc73eab0793870439cf43852a9689d24715a7aa60db7\""
  time="2023-03-28T16:33:41Z" level=fatal msg="exit status 1"
  [FAILED] in [It] - /Users/ec2-user/go/pkg/mod/github.com/runfinch/common-tests@v0.6.2/command/command.go:122 @ 03/28/23 16:33:41.945
  No containers to be removed
```

**Additional context**

### PR DESCRIPTION
**Pull request by pendo324**
Issue #, if available: fixes #322

*Description of changes:*
  - Uses the local registry to run Virtualization framework and Rosetta suites

*Testing done:*
  - Local testing

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by pendo324** [comment]
Looks like there's one remaining issue of the http default server never being cleaned up, which causes a "duplicate handler for /" error.

File: e2e/vm/vm_test.go [hunk 1]
```diff
@@ -82,3 +84,16 @@ var resetVM = func(o *option.Option, installed bool) string {
...
+	if installed {
+		path, err := exec.LookPath(e2e.InstalledTestSubject)
+		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		realFinchPath, err := filepath.EvalSymlinks(path)
+		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		gomega.Expect(os.RemoveAll(filepath.Join(realFinchPath, "../../lima/data/_disks")))
+	} else {
+		gomega.Expect(os.RemoveAll("../../_output/lima/data/_disks")).ShouldNot(gomega.HaveOccurred())
+	}
+	gomega.Expect(os.RemoveAll(path.Join(os.Getenv("HOME"), ".finch", ".disks"))).ShouldNot(gomega.HaveOccurred())
```
Comment (sam-berning) [inline e2e/vm/vm_test.go:98]: I think this should work for runners but it seems overly broad for local e2e testing as it would delete the installed version's disk as well. Maybe it'd be better to follow the symlink for `../lima/data/_disks/finch/datadisk`?

File: e2e/vm/vm_test.go [hunk 2]
```diff
@@ -82,3 +84,16 @@ var resetVM = func(o *option.Option, installed bool) string {
...
 	return limaConfigFilePath
 }
+
+var resetDisks = func(o *option.Option, installed bool) {
+	if installed {
+		path, err := exec.LookPath(e2e.InstalledTestSubject)
+		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		realFinchPath, err := filepath.EvalSymlinks(path)
+		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		gomega.Expect(os.RemoveAll(filepath.Join(realFinchPath, "../../lima/data/_disks")))
```
Comment (sam-berning) [inline e2e/vm/vm_test.go:94]: we should delete the underlying disk in this case too

File: e2e/vm/vm_test.go (hunk 1 above)
Comment (pendo324) [reply e2e/vm/vm_test.go:98]: Good point, I'll update it. Would be nice if we had the disk delete command merged in Finch

Comment (sam-berning) [reply e2e/vm/vm_test.go:98]: yeah, I can revisit that

File: e2e/vm/vm_test.go (hunk 2 above)
Comment (pendo324) [reply e2e/vm/vm_test.go]: updated in latest rev

File: e2e/vm/vm_test.go (hunk 1 above)
Comment (pendo324) [reply e2e/vm/vm_test.go]: updated in latest rev

File: e2e/vm/vm_test.go [hunk 3]
```diff
@@ -82,3 +85,24 @@ var resetVM = func(o *option.Option, installed bool) string {
...
+		realFinchPath, err := filepath.EvalSymlinks(path)
+		gomega.Expect(err).ShouldNot(gomega.HaveOccurred())
+		dataDiskDir = filepath.Join(realFinchPath, "../../", limaDisksPath)
+	} else {
+		dataDiskDir = filepath.Join("../../_output/", limaDisksPath)
+	}
+	realDiskPath, err := os.Readlink(filepath.Join(dataDiskDir, "finch/datadisk"))
+	if err == nil {
+		gomega.Expect(os.Remove(realDiskPath)).ShouldNot(gomega.HaveOccurred())
+	} else if !errors.Is(err, fs.ErrExist) {
```
Comment (sam-berning) [inline e2e/vm/vm_test.go:104]: should be `fs.ErrNotExist`

Comment (pendo324) [reply e2e/vm/vm_test.go]: Fixed, thanks

**Review by sam-berning — APPROVED** [review]
LGTM!

**Comment by pendo324** [comment]
Overriding merge, last test run just had a flaky compose test (known issue).
